### PR TITLE
Change loss computation

### PR DESCRIPTION
**Pull request by nbrinckm**
Updated handling of population and replacement costs from the exposure model.

+ Usage of the replacement costs from exposure model for the loss computation to provide country dependent loss values.
- Removed not used classes & their tests.

### CODE REVIEW

**Comment by nbrinckm** [comment]
> Many thanks for those changes!
> Could you fix all the checks that we have in our pipeline?
> https://travis-ci.com/github/gfzriesgos/deus/jobs/332339150

Sorry, I missed the create_new_loss_file.py, because it was only a help script.
I fixed the pep8 issues.

**Comment by nbrinckm** [comment]
> The heavy increase in computation time should be considered. If this is still OK, we can merge it now, but I would not recommend it...

Let me try some things to improve the performance...

**Comment by nbrinckm** [comment]
I spent way to much time for the optimization, but now I'm on the point that it is way (way!!!) faster. I still hope that I haven't broken something.

**Comment by ruester** [comment]
> I spent way to much time for the optimization, but now I'm on the point that it is way (way!!!) faster. I still hope that I haven't broken something.

This is time spent well :wink: Thanks a lot for this optimization!

**Pull request merged**
